### ISSUE TITLE
cross post editing

### ISSUE THREAD

**Issue by jonay2000** [RobbinBaauw/CSHub#133]
When two different posts are edited at the same time, if one person types in one post it (may) show up in the other post.

**Comment by NULLx76** [comment]
Screenshots: https://imgur.com/a/6qCYfou

**Comment by RobbinBaauw** [comment]
Thats.... Very interesting lol

**Comment by jonay2000** [comment]
no clue, i dont know how it happened, it just happened at some point

**Comment by jonay2000** [comment]
afaik it always happens

**Comment by RobbinBaauw** [comment]
And if you refresh it's gone?

**Comment by jonay2000** [comment]
@NULLx76 and me just retried it

**Comment by jonay2000** [comment]
yeah refreshing removes it

**Comment by NULLx76** [comment]
But it shouldn't even show up of course

**Comment by RobbinBaauw** [comment]
Okay then I have a hunch as to where something is wrong

**Comment by jonay2000** [comment]
good

**Comment by RobbinBaauw** [comment]
Closed by https://github.com/RobbinBaauw/CSHub/commit/b80d5b7b2460343cee044c1657d78abef7f73df4
