### ISSUE TITLE
Scrolling in iOS bugs out

### ISSUE THREAD

**Issue by timanema** [RobbinBaauw/CSHub#136]
**Describe the bug**
When scrolling through a post on iOS (tested with safari and chrome) sometimes instead of scrolling through the post you move the page itself. I have not figured out what triggers it, but on a decent (seemingly random) amount of posts this bug happens.
When this happens you can only scroll through the page by scrolling over the scrollbar directly, otherwise you will just move the page.

Video: https://youtu.be/CujM4UfKuVI

**Comment by NULLx76** [comment]
Is it consistent on which posts it happens? If so could you please link the offending ones?
