### ISSUE TITLE
Direct header links

### ISSUE THREAD

**Issue by jonay2000** [RobbinBaauw/CSHub#151]
I just wanted to link to a specific part of a post. It would be great if there was some way to get a link to a specific (markdown) header in a post (like github permalinks to lines of code). No clue if its implementable or how but it might be nice :)

**Comment by RobbinBaauw** [comment]
Yeah it's doable. There's a few possibilities:
- Parsing headers (maybe h1 thru h3) and using the texts there as ids (this stays the same over multiple edits)
- Using line numbers (harder to implement), but this doesn't remain the same over edits, so you'd have to put some sort of edit identifier in the URL (harder to implement)

**Comment by jonay2000** [comment]
I'm more for the first one. Headers is fine. Direct line numbering isn't necessarily useful. Just being able to reference a part of say, the cn summaries is very useful though

**Comment by RobbinBaauw** [comment]
Hope it works :) 

In order for these ids to be added though, we have to either edit and resave the post, or hit the force save button (the gavel)
