### ISSUE TITLE
Multi study support 

### ISSUE THREAD

**Issue by RobbinBaauw** [RobbinBaauw/CSHub#161]
We should expand to multiple studies. Per study you get:
- Topics
- Admins

You can select a study in some dropdown window, and this will be saved to your localstorage in order to remember which study you want to go to.

If you log in, you automatically go your default study. In the user panel you can select your default study.

Which persons are admins of which studies should be selectable in one big matrix.

We should maybe support different logo's / colors per study

**Comment by NULLx76** [comment]
We could take inspiration from how Slack/Mattermost does this: [mattermost docs](https://docs.mattermost.com/help/getting-started/creating-teams.html).

**Comment by RobbinBaauw** [comment]
Closed by https://github.com/RobbinBaauw/CSHub/commit/c39a210fc7108427feb082c922fbec726fd910d3, implemented the following way:
- Each study has a corresponding topic, which will act as the parent topic of this study, each topic beneath this parent topic also belongs to the topic
- Studies can have duplicate parent topics, or some studies can have a corresponding topic which is a parent topic to another topic 
- A user can be study admins of multiple studies, if they are admin they can save posts, delete posts, mark posts as wip, force edit posts and squash edits for their specific studies
- A normal admin can do all of the previous for all of the studies

I barely tested this but we'll do that later, once all the features are in ;)
- A user is not linked to a study
