### ISSUE TITLE
Quill image and video resizing doesn't work / isn't implemented

### ISSUE THREAD

**Issue by RobbinBaauw** [RobbinBaauw/CSHub#19]
**Is your feature request related to a problem? Please describe.**
If you copy an image / insert a vidoe into the quill component, resizing isn't possible

**Describe the solution you'd like**
Something like this should be implemented: https://github.com/kensnyder/quill-image-resize-module, he has a video resize module as well.

**Comment by victorheld** [comment]
Tried to get it working in various ways, haven't been successful yet, will look more at it later. (May need to build my own version. npm version is definitely not working)

**Comment by RobbinBaauw** [comment]
In an old project I got it working:
- https://github.com/RobbinBaauw/Zaagmolen/tree/master/Website/src/assets/plugins
- https://github.com/RobbinBaauw/Zaagmolen/blob/master/Website/src/main.js

Dont ask me how, but I found references in these files (also please ignore the awful code, it just had to work ;)
