### ISSUE TITLE
Change main colour

### ISSUE THREAD

**Issue by Selawen** [RobbinBaauw/CSHub#20]
**Is your feature request related to a problem? Please describe.**
Not a problem, more a design choice

**Describe the solution you'd like**
Change the main colour to the colour the TU uses

**Additional context**
This is in the correct colour
![image](https://user-images.githubusercontent.com/37039183/46727172-40369800-cc80-11e8-8cd9-3976954800f0.png)

**Comment by RobbinBaauw** [comment]
Go ahead, added you as collaborator. In [this](https://github.com/RobbinBaauw/CSHub/blob/master/faq-site-client/src/App.vue) file you can add global style overwrites.

**Comment by victorheld** [comment]
For reference the correct colour is `##00A6D8`
