### ISSUE TITLE
Quill tables

### ISSUE THREAD

**Issue by RobbinBaauw** [RobbinBaauw/CSHub#24]
**Describe the solution you'd like**
Tables are too important to be left out I'm afraid

**Additional context**
See the slab.com website

**Comment by victorheld** [comment]
Maybe just switching to a markdown editor is a better idea than trying to shove everything into quill.

**Comment by RobbinBaauw** [comment]
We get our html output from quill, recognize markdown, put it through a parser and it will be saved correctly

**Comment by victorheld** [comment]
I actually dislike the WYSIWYG aspect of Quill. Math can still be done in markdown using something like mathquill. However using a parser is also a solution (albeit that the WYSIWYG feature is gone when we do that unless we run the parser continuously)

**Comment by RobbinBaauw** [comment]
Hm, I kinda like quill tbh.

About the markdown, I think it's best to just make a button for that. Running it on change is possible, but might not be handy in terms of it parsing information that is useful later on.

Though I will try to add quill-table and edit it so it is useful for us

**Comment by victorheld** [comment]
I had quite some trouble implementing quill and its modules which is why I may be a bit biased. Will the button parse everything or maybe just the current selection as I know that quill has methods for getting the currently selected text and that won't mess with other stuff that is unintentionally valid markdown.

**Comment by RobbinBaauw** [comment]
Resolved by https://github.com/RobbinBaauw/CSHub/commit/e8d01ceb9e86ce4bfc7af0607b13a3fcf87a0d56
