### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by victorheld** [RobbinBaauw/CSHub#25]
Currently the version milestones are quite arbitrary maybe we could switch to a predefined syntax like [semver](https://semver.org/) which takes on the form `MAJOR.MINOR.PATCH` and will mean that our first release will be `0.1.0` and the second one being `0.2.0` etc. Which makes the version numbers more meaningful and clearer to understand.

**Comment by RobbinBaauw** [comment]
Yes sure

**Comment by victorheld** [comment]
I've changed the versions of the milestones so I'll consider this issue resolved now.
