### ISSUE TITLE
Search function

### ISSUE THREAD

**Issue by RobbinBaauw** [RobbinBaauw/CSHub#26]
**Describe the solution you'd like**
The search bar doesn't do anything yet, it should search for posts

**Additional context**
We should decide how we rank posts, on date or some other measure. We also save the result as HTML, not as text, but we should only search on text

**Comment by NULLx76** [comment]
Fuzzy search would be preferable

**Comment by RobbinBaauw** [comment]
https://cse.google.com/cse/ could be used as well

**Comment by RobbinBaauw** [comment]
I think we need to write a sitemap generator, reading our router files and all the posts + topics from the DB
