### ISSUE TITLE
Mail account create verify

### ISSUE THREAD

**Issue by RobbinBaauw** [RobbinBaauw/CSHub#32]
**Describe the solution you'd like**
We need the user to verify their email address before they can create their account. So we need to setup some sort of mail server from which we can use something like [Nodemailer](https://nodemailer.com/about/) to send emails

**Comment by victorheld** [comment]
I've got my own mail server we could use but probably using something like [sendgrid](https://sendgrid.com/free/) is a better solution

**Comment by victorheld** [comment]
Sendgrid als has a REST api which is easier than using SMTP I think https://sendgrid.com/docs/for-developers/sending-email/api-getting-started/

**Comment by RobbinBaauw** [comment]
Looks good and easy to implement! Shall I make it or do you want to?

**Comment by victorheld** [comment]
Aparrently they even have a node js api we could use https://sendgrid.com/docs/for-developers/sending-email/v3-nodejs-code-example/

**Comment by RobbinBaauw** [comment]
Yup saw so, one thing we could also do is also use the Exchange API of the TU mail to actually check existence of the email address before sending, but that would require one person putting their password in the application somewhere, which I don't really like and this might be unnecessary.
