### ISSUE TITLE
Automated Deployment

### ISSUE THREAD

**Issue by NULLx76** [RobbinBaauw/CSHub#35]
Automated deployment of the site would be a cool/nice thing to have. It would be even nicer if it could automatically migrate the database.

**Describe the solution you'd like**
I know we can do something with Travis to automate deployment, we could probably get it to trigger if we tag a commit with a version number. Don't know how it works exactly though, is something to figure out.

**Describe alternatives you've considered**
We could also just make a bash script to pull the repo, npm install etc. or even better make a docker container so it doesn't interfere with other services.

**Comment by RobbinBaauw** [comment]
Closed in https://github.com/RobbinBaauw/CSHub/pull/100
