### ISSUE TITLE
Can resize picture in viewer

### ISSUE THREAD

**Issue by RobbinBaauw** [RobbinBaauw/CSHub#36]
**Describe the bug**
Read the title

**To Reproduce**
Open post with image and try to resize.

**Expected behavior**
You should not be able to

**Comment by Selawen** [comment]
I think it is a good thing to be able to resize the pic in the viewer, as long as it isn't permanent and only the one that resized the pic can see the difference.

**Comment by NULLx76** [comment]
It is a feature not a bug! (:joy:) but the changes are most definitely not permanent nothing gets saved, even a refresh should clear the change

**Comment by RobbinBaauw** [comment]
I have no clue why you should be able to resize

**Comment by RobbinBaauw** [comment]
Hm, I'd vouch for the ability to click on an image and viewing the full screen dialog

**Comment by Selawen** [comment]
That's also an option. But why purposefully change something that already works?

**Comment by RobbinBaauw** [comment]
I find it kinda ugly rn, that you are able to 'edit' the post
