### ISSUE TITLE
Infinite scrolling on posts

### ISSUE THREAD

**Issue by NULLx76** [RobbinBaauw/CSHub#39]
**Describe the bug**
You can only see 5 items at a time, (only on the frontend).

**To Reproduce**
Use the site.

**Expected behaviour**
Infinite scrolling

**Comment by RobbinBaauw** [comment]
See line https://github.com/RobbinBaauw/CSHub/blob/93aa2a245cf929912a52d14980abc91ebb7c073a/faq-site-client/src/views/user/UserDashboard.vue#L125, here you only see only once the call is made to the server, which should be on scroll etc.
