### ISSUE TITLE
Add extra information to topics

### ISSUE THREAD

**Issue by NULLx76** [RobbinBaauw/CSHub#41]
**Describe the solution you'd like**
Maybe add an extra column to the topics table with extra tags to identify it like course code, which quarter, etc.

Which then can be used by the search function (#26) to get better results.

**Comment by RobbinBaauw** [comment]
Linked to #113

**Comment by RobbinBaauw** [comment]
Closed by https://github.com/RobbinBaauw/CSHub/commit/1d765f336f3cfe23b8d23557ee9b1dc3183ec339
