### ISSUE TITLE
Fix service worker, manifest color and favicon

### ISSUE THREAD

**Issue by RobbinBaauw** [RobbinBaauw/CSHub#43]
**Describe the bug**
The service worker caches too much, you need to do force refresh to actually update etc. 

In the manifest.json the color is still the default Vue color, should be the blue TU color. 

Also, the favicon doesn't seem to update.

**Comment by NULLx76** [comment]
Favicon may actually be overridden by the manifest.json as that still specifies a Vue logo

**Comment by RobbinBaauw** [comment]
Seems true, yes. This is what I meant with not directly committing and opening a PR.... :wink:

**Comment by NULLx76** [comment]
Vue pwa/sw docs:
* https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/cli-plugin-pwa
