### ISSUE TITLE
Indicator when no connection

### ISSUE THREAD

**Issue by Selawen** [RobbinBaauw/CSHub#45]
**Is your feature request related to a problem? Please describe.**
There is nothing to indicate when your connection is compromised.

**Describe the solution you'd like**
Some kind of indicator to show you have no connection.

**Describe alternatives you've considered**
Text where the post should be.
Error popup when no connection is detected

**Additional context**
When you have no connection you can't see the post, if you don't know you don't have a connection that is very confusing.

**Comment by RobbinBaauw** [comment]
Yeah well, it's something for the future indeed, giving more feedback to the user. I'll make a 0.3.0 milestone and move some things I think belong to that, which would include this one

**Comment by RobbinBaauw** [comment]
@NULLx76 a quick addition for the UX one, also show a confirmation box when editing / creating a post and destroying the quill component (aka leafing the page)

**Comment by NULLx76** [comment]
Relevant link for reference
* https://developers.google.com/web/fundamentals/instant-and-offline/offline-ux

**Comment by RobbinBaauw** [comment]
Closing as #131 is the issue that contains this
