### ISSUE TITLE
Quill to HTML converter 

### ISSUE THREAD

**Issue by RobbinBaauw** [RobbinBaauw/CSHub#50]
**Describe the solution you'd like**
There should be a quill to HTML converter. There exists a library for that already: https://github.com/nozer/quill-delta-to-html. We should just add highlightjs and katex support

**Comment by NULLx76** [comment]
Kinda fixed in 8a83f743f9f4188c0d7e735520616c36a859dbf1 still needs testing though.

**Comment by NULLx76** [comment]
This also resolves #36
