### ISSUE TITLE
Remove jQuery

### ISSUE THREAD

**Issue by RobbinBaauw** [RobbinBaauw/CSHub#52]
**Describe the bug**
Right now we have a dependency on jQuery, which is deffo a bug

**Comment by NULLx76** [comment]
Mathquill is depending on jquery see code snippets below:
* [snip1](https://github.com/mathquill/mathquill/blob/23a0e88c80c79514ffc30ead490bd880306bce2a/src/services/saneKeyboardEvents.util.js#L95)
* [snip2](https://github.com/mathquill/mathquill/blob/23a0e88c80c79514ffc30ead490bd880306bce2a/src/services/textarea.js#L51)
* [snip3](https://github.com/mathquill/mathquill/blob/23a0e88c80c79514ffc30ead490bd880306bce2a/test/unit/saneKeyboardEvents.test.js#L4)

If we implement these methods ourselves/replace them in our mathquill version we should be able to ditch  jquery as a dependency

**Comment by RobbinBaauw** [comment]
Yeah and https://github.com/RobbinBaauw/CSHub/blob/dev/cshub-client/src/components/posts/Post.vue#L130 is the only place in our application where it's used

**Comment by RobbinBaauw** [comment]
Closing as the only way to do this is by removing mathquill. As we won't be working on the old editor anymore it's not worth it to try and remove it
