### ISSUE TITLE
Hard to hit the treeview button

### ISSUE THREAD

**Issue by RobbinBaauw** [RobbinBaauw/CSHub#56]
**Describe the bug**
Mostly on mobile it is very hard to expand the topic tree view

**Comment by RobbinBaauw** [comment]
Fixed in #62

**Comment by RobbinBaauw** [comment]
I tried that, but it's only one level on which it works reliably

**Comment by NULLx76** [comment]
Interesting as it clearly shows two levels in the example, but I can see that it could be difficult nesting it infinitely and/or programatically. I'm not quite keen on the current implementation though so maybe I'll try implemting this or trying some other alternatives.
