### ISSUE TITLE
ORM

### ISSUE THREAD

**Issue by RobbinBaauw** [RobbinBaauw/CSHub#7]
For testing purposes, it would be nice to have a different database, though somehow the structure must be the same between databases (plugin?)

**Comment by NULLx76** [comment]
Maybe migrating to MongoDB / Mongoose is also a possibility, it seems better to integrate with JS/TS.

* [Mongoose](https://mongoosejs.com/docs/index.html)
* [MongoDB](https://www.mongodb.com/)
