### ISSUE TITLE
Mouseover Tooltips

### ISSUE THREAD

**Issue by Closer11** [RobbinBaauw/CSHub#83]
When logged in to CShub as admin and viewing a post, in the top right corner are multiple buttons. Besides the icons these have no indication of what they do. My suggestion is to have a short keyword or description of what the button does when hovering over the button.

**Comment by NULLx76** [comment]
IMO admin stuff doesn't really need explanations as only admins can see it and they should know what everything does. If we do add this it's definitely low priority

**Comment by RobbinBaauw** [comment]
Besides, I think the icons arent that unclear, the history icon opens the history, the arrow up closes the menu up, save saves, edit edits

**Comment by NULLx76** [comment]
If you want it you can add it yourself, marking it as wontfix.
