### ISSUE TITLE
language selection in codeblocks

### ISSUE THREAD

**Issue by jonay2000** [RobbinBaauw/CSHub#84]
language menu on code blocks sometimes doesnt show all options as in visible in this image:
![image](https://user-images.githubusercontent.com/22172241/50141481-dc47d580-02a7-11e9-8697-8ca0af01c9f3.png)

i think you can reproduce this by just opening the editor but sometimes it does work properly

it should show all options in black (i think the problem is that the other options are there but the color is the same as the background. backed by the chrome inspector view)

**Comment by RobbinBaauw** [comment]
Closing as in the newest update this doesn't exist anymore :)
