### ISSUE TITLE
up/downvotes and a ranking system

### ISSUE THREAD

**Issue by jonay2000** [RobbinBaauw/CSHub#85]
i think this one is quite clear :)
use this context to help with sorting searchlists. give people with more upvotes higher rankings. display ranks with username. etcetera

**Comment by RobbinBaauw** [comment]
I'm editing your request as the upvoting system is already requested (https://github.com/RobbinBaauw/CSHub/issues/42), but the rest isn't

**Comment by RobbinBaauw** [comment]
Not needed as we want "the best" post instead of multiple posts which are upvoted. We will show a list of people that have worked on a post.
