### ISSUE TITLE
metatags for discord embedded links

### ISSUE THREAD

**Issue by jonay2000** [RobbinBaauw/CSHub#86]
make it so in discord or other messaging services, links will be expanded to show for example the logo and other info. kinda like this:
![image](https://user-images.githubusercontent.com/22172241/50141799-b4a53d00-02a8-11e9-8b9f-01474ab7ed08.png)

**Comment by NULLx76** [comment]
Nevermind, still doesn't work. As we are using VueJS and thus by extension JS for rendering and routing most things, and Discord (of course) doesn't execute JS. Therefore we need to add SSR or something similar to "man-in-the-middle" the requests and then add the meta tags dynamically to the html before sending it through.

In conclusion, we need to think hard on how/if we want to do this. Any input on this matter is greatly appreciated.

**Comment by RobbinBaauw** [comment]
Fixed in https://github.com/RobbinBaauw/CSHub/commit/394207262a8ebac4f3c06d5512f7882fc0d16690
