### ISSUE TITLE
enter on elements doesnt exit it

### ISSUE THREAD

**Issue by jonay2000** [RobbinBaauw/CSHub#90]
when pressing enter in for example a codeblock, you stay in the codeblock and it will be enlarged. however sometimes this is not what you want. you actually want a new line below. in many cases this is trivial because you just click below the codeblock. it is however a problem when the codeblock is the last line in a post because then there is no line below to click on. 

solution: add a control-enter or shift-enter to exit block and newline

**Comment by RobbinBaauw** [comment]
Closing in favor of #190
